[
  # False positive from code generated by the Phoenix.Router macros.
  {"deps/phoenix/lib/phoenix/router.ex", :pattern_match},
  # False positive from the child_spec/1 generated by `use Commanded.Application`, reported
  # once code calls Ledger.App.dispatch/1. The app starts fine in every integration test.
  {"lib/ledger/app.ex", :no_return}
]
